export const i18n = {
  es: {
    sectionLabel: 'Municipios',
    footerBrand: 'Chiapas · México',
    aboutTitle: 'Sobre Chiapas',
    aboutText: 'Chiapas es una tierra de culturas ancestrales, tradiciones vibrantes y una belleza natural impresionante. Este estado del sur de México es hogar de las civilizaciones Maya y Tzeltal, cuyo patrimonio se celebra a través de festivales coloridos y rituales sagrados durante todo el año. Desde ciudades coloniales hasta tierras altas indígenas, Chiapas es donde late el corazón de México con más fuerza.',
    municipalities: ['Tuxtla Gutiérrez', 'San Juan Chamula', 'Chiapa de Corzo', 'Ocozocoautla', 'San Cristóbal', 'Palenque', 'Comitán', 'Villaflores', 'Tapachula', 'Las Margaritas'],
    data: {
      tuxtla:       { type: 'Capital del Estado',    title: 'Tuxtla Gutiérrez',          text: 'Capital de Chiapas, esta ciudad moderna alberga anualmente la famosa Feria de la Primavera y la Paz, reuniendo tradiciones, artesanías, gastronomía local y espectáculos culturales espectaculares.',                                        tags: ['Feria de Primavera', 'Marzo–Abril', 'Gastronomía', 'Artesanías'], population: '604.000', specialty: 'Comercio y Ferias', history: 'Fundada en 1565, es el centro político y económico del estado.' },
      chamula:      { type: 'Festival Indígena',    title: 'San Juan Chamula',          text: 'Famoso por su Carnaval Tzotzil, uno de los festivales más espectaculares de México. Los Pasiones bailan durante días en honor al sol, fusionando ritos mayas con elementos católicos en perfecta armonía.',                                    tags: ['Carnaval Tzotzil', 'Febrero', 'Danza Ritual', 'Sagrado'], population: '80.000', specialty: 'Rituales Indígenas', history: 'Una comunidad Tzotzil sagrada en las tierras altas con tradiciones prehispánicas ininterrumpidas.' },
      chiapa:       { type: 'Patrimonio UNESCO',    title: 'Chiapa de Corzo',           text: 'Hogar de la legendaria Fiesta Grande de Chiapa, donde la icónica danza de los Parachicos cobra vida cada enero. Reconocida por la UNESCO en 2010 como Patrimonio Cultural Inmaterial de la Humanidad.',                                      tags: ['Parachicos', 'Enero', 'UNESCO', 'Fiesta Grande'], population: '65.000', specialty: 'Danza Tradicional', history: 'Esta joya colonial se asienta en el río Grijalva con más de 500 años de tradición festiva.' },
      ocozocoautla: { type: 'Carnaval Regional',    title: 'Ocozocoautla de Espinosa',  text: 'Conocida cariñosamente como Coita, su carnaval presenta la impresionante danza Quexquemetl y Parachicos locales, una celebración vibrante que mezcla humor, música, marimba y tradición popular auténtica.',                              tags: ['Carnaval', 'Febrero', 'Danza', 'Tradición'], population: '50.000', specialty: 'Danza Popular', history: 'Una comunidad mestiza famosa por fusionar elementos culturales indígenas y españoles.' },
      sancristobal: { type: 'Ciudad Colonial',      title: 'San Cristóbal de las Casas',text: 'Un hermoso centro colonial a 2.200m de altitud, lleno de festividades religiosas durante todo el año. Cada barrio honra a su santo patrón con marimba, fuegos artificiales, procesiones y ferias tradicionales.',                          tags: ['Fiestas Patronales', 'Todo el Año', 'Marimba', 'Colonial'], population: '186.000', specialty: 'Patrimonio Colonial', history: 'Fundada en 1528, sigue siendo el corazón cultural de las tierras altas de Chiapas.' },
      palenque:     { type: 'Sitio Arqueológico',   title: 'Palenque',                  text: 'Hogar de una de las ruinas mayas más importantes y enigmáticas de México. La antigua ciudad de Bakal revela templos y palacios deslumbrantes e inscripciones jeroglíficas en un entorno selvático perdido en el tiempo.',                      tags: ['Ruinas Mayas', 'Arqueología', 'Selva', 'Historia'], population: '45.000', specialty: 'Cultura Maya Ancestral', history: 'El apogeo de la ciudad fue 600-800 dC, representando la altura de la civilización Maya Clásica.' },
      comitan:      { type: 'Pueblo de Montaña',    title: 'Comitán de Domínguez',     text: 'Un encantador pueblo colonial en las tierras altas conocido por sus lagos, clima templado y cultura indígena Tzeltal. Famoso por sus arreglos florales y proximidad a las impresionantes Lagunas de Montebello.',                        tags: ['Lagos', 'Clima Montañoso', 'Ruta de Lagos', 'Ecología'], population: '142.000', specialty: 'Naturaleza y Lagos', history: 'Fundada en 1564, es la puerta de entrada a las más hermosas reservas naturales de Chiapas.' },
      villaflores:  { type: 'Región Cafetalera',    title: 'Villaflores',              text: 'Este paraíso agrícola es conocido como la capital del café de Chiapas, produciendo algunos de los mejores granos arábigos de México. La región ofrece plantaciones de café, turismo ecológico y clima tropical cálido.',                  tags: ['Café', 'Agricultura', 'Ecología', 'Plantaciones'], population: '35.000', specialty: 'Café Premium', history: 'Desde 1900, el cultivo del café ha moldeado la identidad de esta región.' },
      tapachula:    { type: 'Ciudad Fronteriza',    title: 'Tapachula',                text: 'La ciudad más tropical de Chiapas, ubicada en la frontera con Guatemala. Conocida por las plantaciones de cacao, mercados vibrantes y su papel como centro importante de comercio e intercambio cultural entre México y América Central.',    tags: ['Cacao', 'Comercio', 'Tropical', 'Mercados'], population: '328.000', specialty: 'Cacao y Comercio', history: 'Un antiguo asentamiento Maya que se convirtió en un importante puesto comercial regional.' },
      margaritas:   { type: 'Aldea de Montaña',     title: 'Las Margaritas',           text: 'Una comunidad de las tierras altas conocida por sus tradiciones indígenas Tzeltal, tejidos tradicionales y celebraciones comunitarias auténticas. La ciudad ofrece a los visitantes una visión genuina de la vida indígena contemporánea.',   tags: ['Tejidos Indígenas', 'Artesanías', 'Tierras Altas', 'Cultura'], population: '28.000', specialty: 'Tejidos Tradicionales', history: 'Un ejemplo vivo de cómo las tradiciones indígenas continúan floreciendo en Chiapas moderno.' },
    },
  },
  en: {
    sectionLabel: 'Municipalities',
    footerBrand: 'Chiapas · Mexico',
    aboutTitle: 'About Chiapas',
    aboutText: 'Chiapas is a land of ancient cultures, vibrant traditions, and breathtaking natural beauty. This southern Mexican state is home to the Mayan and Tzeltal civilizations, whose heritage is celebrated through colorful festivals and sacred rituals throughout the year. From colonial cities to indigenous highlands, Chiapas is where Mexico\'s heart beats strongest.',
    municipalities: ['Tuxtla Gutiérrez', 'San Juan Chamula', 'Chiapa de Corzo', 'Ocozocoautla', 'San Cristóbal', 'Palenque', 'Comitán', 'Villaflores', 'Tapachula', 'Las Margaritas'],
    data: {
      tuxtla:       { type: 'State Capital',         title: 'Tuxtla Gutiérrez',          text: 'Capital of Chiapas, this modern city hosts the famous Spring and Peace Fair annually, bringing together traditions, crafts, local gastronomy and spectacular cultural shows.',                                                          tags: ['Spring Fair', 'March–April', 'Gastronomy', 'Crafts'], population: '604,000', specialty: 'Fair & Commerce', history: 'Founded in 1565, it is the political and economic center of the state.' },
      chamula:      { type: 'Indigenous Festival',   title: 'San Juan Chamula',          text: 'Famous for its Tzotzil Carnival, one of the most spectacular festivals in Mexico. The Pasiones dance for days in honor of the sun, blending Mayan and Catholic rites in perfect harmony.',                                                     tags: ['Tzotzil Carnival', 'February', 'Ritual Dance', 'Sacred'], population: '80,000', specialty: 'Indigenous Rituals', history: 'A sacred Tzotzil community in the Chiapas highlands with unbroken pre-Hispanic traditions.' },
      chiapa:       { type: 'UNESCO Heritage',       title: 'Chiapa de Corzo',           text: 'Home to the legendary Fiesta Grande de Chiapa, where the iconic Parachicos dance comes alive every January. Recognized by UNESCO in 2010 as Intangible Cultural Heritage of Humanity.',                                                         tags: ['Parachicos', 'January', 'UNESCO', 'Fiesta Grande'], population: '65,000', specialty: 'Traditional Dance', history: 'This colonial gem sits on the Grijalva River with 500+ years of festive tradition.' },
      ocozocoautla: { type: 'Regional Carnival',     title: 'Ocozocoautla de Espinosa',  text: 'Known affectionately as Coita, its carnival features the stunning Quexquemetl dance and local Parachicos, a vibrant celebration mixing humor, music, marimba and authentic folk traditions.',                                            tags: ['Carnival', 'February', 'Dance', 'Tradition'], population: '50,000', specialty: 'Folk Dance', history: 'A mestizo community famous for blending indigenous and Spanish cultural elements.' },
      sancristobal: { type: 'Colonial City',         title: 'San Cristóbal de las Casas',text: 'A beautiful colonial center at 7,400 ft elevation, full of religious festivals year-round. Each neighborhood honors its patron saint with marimba, fireworks, processions and traditional fairs.',                                        tags: ['Patron Festivals', 'Year-round', 'Marimba', 'Colonial'], population: '186,000', specialty: 'Colonial Heritage', history: 'Founded in 1528, it remains the cultural heart of the Chiapas highlands.' },
      palenque:     { type: 'Archaeological Site',   title: 'Palenque',                  text: 'Home to one of the most important and enigmatic Mayan ruins in Mexico. The ancient city of Bakal reveals stunning temples, palaces, and hieroglyphic inscriptions in a jungle setting lost to time.',                                         tags: ['Mayan Ruins', 'Archaeology', 'Jungle', 'History'], population: '45,000', specialty: 'Ancient Mayan Culture', history: 'Peak of the city was 600-800 AD, representing the height of Classic Mayan civilization.' },
      comitan:      { type: 'Mountain Town',         title: 'Comitán de Dominguez',     text: 'A charming colonial town in the highlands known for its lakes, temperate climate, and indigenous Tzeltal culture. Famous for its floral arrangements and proximity to the stunning Lagunas de Montebello.',                                    tags: ['Lakes', 'Mountain Climate', 'Lakes Trail', 'Ecology'], population: '142,000', specialty: 'Nature & Lakes', history: 'Founded in 1564, it is a gateway to Chiapas\' most beautiful natural reserves.' },
      villaflores:  { type: 'Coffee Region',         title: 'Villaflores',              text: 'This agricultural paradise is known as the coffee capital of Chiapas, producing some of Mexico\'s finest arabica beans. The region offers coffee plantations, ecological tourism and a warm tropical climate.',                           tags: ['Coffee', 'Agriculture', 'Ecology', 'Plantations'], population: '35,000', specialty: 'Premium Coffee', history: 'Since the 1900s, coffee cultivation has shaped the identity of this region.' },
      tapachula:    { type: 'Border City',           title: 'Tapachula',                text: 'Chiapas\' most tropical city, located on the Guatemala border. Known for cacao plantations, vibrant markets, and its role as a major commerce and cultural exchange hub between Mexico and Central America.',                                tags: ['Cacao', 'Trade', 'Tropical', 'Markets'], population: '328,000', specialty: 'Cacao & Commerce', history: 'An ancient Mayan settlement that became a vital trading post for regional commerce.' },
      margaritas:   { type: 'Highland Village',      title: 'Las Margaritas',           text: 'A highland community known for its indigenous Tzeltal traditions, traditional weaving, and authentic community celebrations. The town offers visitors a genuine glimpse into contemporary indigenous Chiapas life.',                              tags: ['Indigenous Weaving', 'Crafts', 'Highlands', 'Culture'], population: '28,000', specialty: 'Traditional Weaving', history: 'A living example of how indigenous traditions continue to thrive in modern Chiapas.' },
    },
  },
  pt: {
    sectionLabel: 'Municípios',
    footerBrand: 'Chiapas · México',
    aboutTitle: 'Sobre Chiapas',
    aboutText: 'Chiapas é uma terra de culturas ancestrais, tradições vibrantes e beleza natural impressionante. Este estado do sul do México é lar das civilizações Maia e Tzeltal, cujo patrimônio é celebrado através de festivais coloridos e rituais sagrados o ano todo. Das cidades coloniais às terras altas indígenas, Chiapas é onde o coração do México bate mais forte.',
    municipalities: ['Tuxtla Gutiérrez', 'San Juan Chamula', 'Chiapa de Corzo', 'Ocozocoautla', 'San Cristóbal', 'Palenque', 'Comitán', 'Villaflores', 'Tapachula', 'Las Margaritas'],
    data: {
      tuxtla:       { type: 'Capital do Estado',     title: 'Tuxtla Gutiérrez',          text: 'Capital de Chiapas, realiza a Feira da Primavera e da Paz todo ano, reunindo tradições, artesanato, gastronomia local e espetáculos culturais espetaculares.',                                                                            tags: ['Feira da Primavera', 'Março–Abril', 'Gastronomia', 'Artesanato'], population: '604.000', specialty: 'Comércio e Feiras', history: 'Fundada em 1565, é o centro político e econômico do estado.' },
      chamula:      { type: 'Festividade Indígena',  title: 'San Juan Chamula',          text: 'Famoso pelo Carnaval Tzotzil, uma das festas mais impressionantes do México. Os Pasiones dançam por dias em honra ao sol, fundindo ritos maias com elementos católicos em perfeita harmonia.',                                            tags: ['Carnaval Tzotzil', 'Fevereiro', 'Dança ritual', 'Sagrado'], population: '80.000', specialty: 'Rituais Indígenas', history: 'Uma comunidade Tzotzil sagrada nas terras altas com tradições pré-hispânicas ininterruptas.' },
      chiapa:       { type: 'Patrimônio UNESCO',     title: 'Chiapa de Corzo',           text: 'Lar da lendária Fiesta Grande de Chiapa, onde a icônica dança dos Parachicos ganha vida todo janeiro. Reconhecida pela UNESCO em 2010 como Patrimônio Cultural Imaterial da Humanidade.',                                                 tags: ['Parachicos', 'Janeiro', 'UNESCO', 'Fiesta Grande'], population: '65.000', specialty: 'Dança Tradicional', history: 'Esta joia colonial fica no Rio Grijalva com 500+ anos de tradição festiva.' },
      ocozocoautla: { type: 'Carnaval Regional',     title: 'Ocozocoautla de Espinosa',  text: 'Conhecida carinhosamente como Coita, seu carnaval destaca a dança Quexquemetl e Parachicos locais, uma celebração vibrante misturando humor, música, marimba e tradição popular autêntica.',                                           tags: ['Carnaval', 'Fevereiro', 'Dança', 'Tradição'], population: '50.000', specialty: 'Dança Popular', history: 'Uma comunidade mestiça famosa por fundir elementos culturais indígenas e espanhóis.' },
      sancristobal: { type: 'Cidade Colonial',       title: 'San Cristóbal de las Casas',text: 'Um lindo centro colonial a 2.200m de altitude, repleto de festividades religiosas o ano todo. Cada bairro honra seu santo padroeiro com marimba, fogos, procissões e feiras tradicionais.',                                               tags: ['Festas patronais', 'Todo o ano', 'Marimba', 'Colonial'], population: '186.000', specialty: 'Patrimônio Colonial', history: 'Fundada em 1528, permanece sendo o coração cultural das terras altas de Chiapas.' },
      palenque:     { type: 'Sítio Arqueológico',    title: 'Palenque',                  text: 'Lar de uma das ruínas Maias mais importantes e enigmáticas do México. A antiga cidade de Bakal revela templos deslumbrantes, palacios e inscrições hieroglíficas perdidos na selva há séculos.',                                        tags: ['Ruínas Maias', 'Arqueologia', 'Selva', 'História'], population: '45.000', specialty: 'Cultura Maia Ancestral', history: 'O auge da cidade foi 600-800 dC, representando a altura da civilização Maia Clássica.' },
      comitan:      { type: 'Cidade de Montanha',    title: 'Comitán de Dominguez',     text: 'Uma charmosa cidade colonial nas terras altas conhecida por seus lagos, clima temperado e cultura indígena Tzeltal. Famosa por seus arranjos florais e proximidade às impressionantes Lagunas de Montebello.',                            tags: ['Lagos', 'Clima Montanhoso', 'Trilha dos Lagos', 'Ecologia'], population: '142.000', specialty: 'Natureza e Lagos', history: 'Fundada em 1564, é porta de entrada para as mais belas reservas naturais de Chiapas.' },
      villaflores:  { type: 'Região Cafeeira',       title: 'Villaflores',              text: 'Este paraíso agrícola é conhecido como a capital do café de Chiapas, produzindo alguns dos melhores grãos arábicos do México. A região oferece plantações de café, turismo ecológico e clima tropical quente.',                           tags: ['Café', 'Agricultura', 'Ecologia', 'Plantações'], population: '35.000', specialty: 'Café Premium', history: 'Desde 1900, o cultivo de café moldou a identidade desta região.' },
      tapachula:    { type: 'Cidade Fronteiriça',    title: 'Tapachula',                text: 'A cidade mais tropical de Chiapas, localizada na fronteira com a Guatemala. Conhecida por plantações de cacau, mercados vibrantes e seu papel como hub importante de comércio e intercâmbio cultural entre México e América Central.',        tags: ['Cacau', 'Comércio', 'Tropical', 'Mercados'], population: '328.000', specialty: 'Cacau e Comércio', history: 'Um antigo assentamento Maia que se tornou um importante posto comercial regional.' },
      margaritas:   { type: 'Aldeia das Terras Altas',title: 'Las Margaritas',           text: 'Uma comunidade das terras altas conhecida por suas tradições indígenas Tzeltal, tecelagem tradicional e celebrações autênticas da comunidade. A cidade oferece aos visitantes um vislumbre genuíno da vida indígena contemporânea.',      tags: ['Tecelagem Indígena', 'Artesanato', 'Terras altas', 'Cultura'], population: '28.000', specialty: 'Tecelagem Tradicional', history: 'Um exemplo vivo de como as tradições indígenas continuam florescendo em Chiapas moderna.' },
    },
  },
}

export const MUNICIPALITY_KEYS = ['tuxtla', 'chamula', 'chiapa', 'ocozocoautla', 'sancristobal', 'palenque', 'comitan', 'villaflores', 'tapachula', 'margaritas']

export const LANGUAGES = [
  { code: 'es', flag: '🇲🇽', label: 'ES', title: 'Español' },
  { code: 'en', flag: '🇺🇸', label: 'EN', title: 'English' },
  { code: 'pt', flag: '🇧🇷', label: 'PT', title: 'Português' },
]
