import type { I18nData, Language, LanguageCode } from '../types'

// Shared photo galleries per festival key (used across all languages)
const festivalPhotos: Record<string, { id: string; url: string; caption?: string }[]> = {
  parachicos: [
    { id: 'p1', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Parachicos_Chiapa_de_Corzo.jpg/1280px-Parachicos_Chiapa_de_Corzo.jpg', caption: 'Danzantes Parachicos en Chiapa de Corzo' },
    { id: 'p2', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Chiapa_de_Corzo_-_panoramio.jpg/1280px-Chiapa_de_Corzo_-_panoramio.jpg', caption: 'Vista de Chiapa de Corzo' },
    { id: 'p3', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Chiapa_de_Corzo_Zocalo.jpg/1280px-Chiapa_de_Corzo_Zocalo.jpg', caption: 'Zócalo de Chiapa de Corzo' },
  ],
  chamula: [
    { id: 'c1', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/San_Juan_Chamula_Chiapas_Mexico.jpg/1280px-San_Juan_Chamula_Chiapas_Mexico.jpg', caption: 'Iglesia de San Juan Chamula' },
    { id: 'c2', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Chamula_church_interior.jpg/1280px-Chamula_church_interior.jpg', caption: 'Interior de la iglesia Tzotzil' },
  ],
  ocozocoautla: [
    { id: 'o1', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Ocozocoautla_de_Espinosa%2C_Chiapas.jpg/1280px-Ocozocoautla_de_Espinosa%2C_Chiapas.jpg', caption: 'Ocozocoautla de Espinosa' },
  ],
  tuxtla: [
    { id: 't1', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Tuxtla_Gutierrez_Chiapas.jpg/1280px-Tuxtla_Gutierrez_Chiapas.jpg', caption: 'Tuxtla Gutiérrez, capital de Chiapas' },
    { id: 't2', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Ca%C3%B1%C3%B3n_del_Sumidero.jpg/1280px-Ca%C3%B1%C3%B3n_del_Sumidero.jpg', caption: 'Cañón del Sumidero' },
  ],
  sancristobal: [
    { id: 's1', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/SanCristobalDeLasCasas.jpg/1280px-SanCristobalDeLasCasas.jpg', caption: 'San Cristóbal de las Casas' },
    { id: 's2', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Catedral_de_San_Crist%C3%B3bal_de_las_Casas.jpg/1280px-Catedral_de_San_Crist%C3%B3bal_de_las_Casas.jpg', caption: 'Catedral colonial' },
    { id: 's3', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/SancrisMarket.jpg/1280px-SancrisMarket.jpg', caption: 'Mercado tradicional' },
  ],
  palenque: [
    { id: 'pa1', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Palenque_Temple_of_the_Inscriptions.jpg/1280px-Palenque_Temple_of_the_Inscriptions.jpg', caption: 'Templo de las Inscripciones' },
    { id: 'pa2', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Palenque_palacio.jpg/1280px-Palenque_palacio.jpg', caption: 'El Palacio de Palenque' },
    { id: 'pa3', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Palenque_ruins.jpg/1280px-Palenque_ruins.jpg', caption: 'Ruinas en la selva' },
  ],
  comitan: [
    { id: 'co1', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Lagos_de_Montebello_Chiapas.jpg/1280px-Lagos_de_Montebello_Chiapas.jpg', caption: 'Lagunas de Montebello' },
    { id: 'co2', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Comitan_Chiapas.jpg/1280px-Comitan_Chiapas.jpg', caption: 'Comitán de Domínguez' },
  ],
  villaflores: [
    { id: 'v1', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Coffea_arabica_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-025.jpg/800px-Coffea_arabica_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-025.jpg', caption: 'Planta de café arábigo' },
    { id: 'v2', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Roasted_coffee_beans.jpg/1280px-Roasted_coffee_beans.jpg', caption: 'Café de Chiapas' },
  ],
  tapachula: [
    { id: 'ta1', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Tapachula_Chiapas.jpg/1280px-Tapachula_Chiapas.jpg', caption: 'Tapachula, ciudad fronteriza' },
    { id: 'ta2', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Cacao_pods_and_cacao_beans.jpg/1280px-Cacao_pods_and_cacao_beans.jpg', caption: 'Cacao de Chiapas' },
  ],
  margaritas: [
    { id: 'm1', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Weaving_in_Chiapas.jpg/1280px-Weaving_in_Chiapas.jpg', caption: 'Tejidos tradicionales Tzeltal' },
    { id: 'm2', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Chiapas_highland_village.jpg/1280px-Chiapas_highland_village.jpg', caption: 'Comunidad de las tierras altas' },
  ],
}

export const i18n: I18nData = {
  es: {
    sectionLabel: 'Festivales',
    footerBrand: 'Chiapas · México',
    aboutTitle: 'Sobre Chiapas',
    aboutText: 'Chiapas es una tierra de culturas ancestrales, tradiciones vibrantes y una belleza natural impresionante. Este estado del sur de México es hogar de las civilizaciones Maya y Tzeltal, cuyo patrimonio se celebra a través de festivales coloridos y rituales sagrados durante todo el año. Desde ciudades coloniales hasta tierras altas indígenas, Chiapas es donde late el corazón de México con más fuerza.',
    festivals: ['Parachicos - Fiesta Grande', 'Carnaval Tzotzil', 'Carnaval Ocozocoautla', 'Feria de la Primavera', 'Fiestas Patronales', 'Ruinas de Palenque', 'Lagunas de Montebello', 'Festival del Café', 'Festival del Cacao', 'Festividades Indígenas'],
    data: {
      parachicos:   { type: 'Patrimonio UNESCO',       title: 'Parachicos - Fiesta Grande',  text: 'La legendaria Fiesta Grande de Chiapa de Corzo donde la icónica danza de los Parachicos cobra vida cada enero. Reconocida por la UNESCO en 2010 como Patrimonio Cultural Inmaterial de la Humanidad. Incluye música, danza, gastronomía y celebración religiosa.',                                                                dates: '7 - 23 de Enero',        municipality: 'Chiapa de Corzo',              tags: ['Danza Tradicional', 'UNESCO', 'Enero', 'Patrimonio'],        specialty: 'Danza Parachicos',         history: 'Esta joya colonial se asienta en el río Grijalva con más de 500 años de tradición festiva.',                                                   photos: festivalPhotos.parachicos },
      chamula:      { type: 'Festival Indígena',       title: 'Carnaval Tzotzil',            text: 'Famoso por su Carnaval Tzotzil, uno de los festivales más espectaculares de México. Los Pasiones bailan durante días en honor al sol, fusionando ritos mayas con elementos católicos en perfecta armonía. Espectáculo de color y tradición.',             dates: 'Fines de Febrero',       municipality: 'San Juan Chamula',             tags: ['Carnaval Tzotzil', 'Danza Ritual', 'Sagrado', 'Ritual'],    specialty: 'Rituales Indígenas',       history: 'Una comunidad Tzotzil sagrada en las tierras altas con tradiciones prehispánicas ininterruptas.',                                              photos: festivalPhotos.chamula },
      ocozocoautla: { type: 'Carnaval Regional',       title: 'Carnaval Ocozocoautla',       text: 'Conocido cariñosamente como Coita, su carnaval presenta la impresionante danza Quexquemetl y Parachicos locales, una celebración vibrante que mezcla humor, música, marimba y tradición popular auténtica. Fiesta de colores y movimiento.',              dates: 'Febrero',                municipality: 'Ocozocoautla de Espinosa',    tags: ['Carnaval', 'Danza', 'Tradición', 'Humor'],                  specialty: 'Danza Popular',            history: 'Una comunidad mestiza famosa por fusionar elementos culturales indígenas y españoles.',                                                         photos: festivalPhotos.ocozocoautla },
      tuxtla:       { type: 'Feria Estatal',           title: 'Feria de la Primavera',       text: 'Capital de Chiapas, esta ciudad moderna alberga anualmente la famosa Feria de la Primavera y la Paz, reuniendo tradiciones, artesanías, gastronomía local y espectáculos culturales espectaculares. Semana de celebración total.',                     dates: 'Marzo - Abril',          municipality: 'Tuxtla Gutiérrez',            tags: ['Feria', 'Gastronomía', 'Artesanías', 'Música'],             specialty: 'Comercio y Ferias',        history: 'Fundada en 1565, es el centro político y económico del estado y sede de la feria más importante de Chiapas.',                                  photos: festivalPhotos.tuxtla },
      sancristobal: { type: 'Festividades Religiosas', title: 'Fiestas Patronales',          text: 'Un hermoso centro colonial a 2.200m de altitud, lleno de festividades religiosas durante todo el año. Cada barrio honra a su santo patrón con marimba, fuegos artificiales, procesiones y ferias tradicionales. Año completo de celebraciones.',        dates: 'Todo el Año',            municipality: 'San Cristóbal de las Casas',  tags: ['Fiestas Patronales', 'Marimba', 'Religioso', 'Procesiones'], specialty: 'Patrimonio Colonial',      history: 'Fundada en 1528, sigue siendo el corazón cultural de las tierras altas de Chiapas.',                                                           photos: festivalPhotos.sancristobal },
      palenque:     { type: 'Sitio Arqueológico',      title: 'Ruinas de Palenque',          text: 'Hogar de una de las ruinas mayas más importantes y enigmáticas de México. La antigua ciudad de Bakal revela templos y palacios deslumbrantes e inscripciones jeroglíficas en un entorno selvático perdido en el tiempo. Patrimonio de la Humanidad.',   dates: 'Visitable Todo el Año',  municipality: 'Palenque',                    tags: ['Ruinas Mayas', 'Arqueología', 'Selva', 'Patrimonio'],       specialty: 'Cultura Maya Ancestral',   history: 'El apogeo de la ciudad fue 600-800 dC, representando la altura de la civilización Maya Clásica.',                                              photos: festivalPhotos.palenque },
      comitan:      { type: 'Destino Ecoturístico',    title: 'Lagunas de Montebello',       text: 'Un encantador pueblo colonial en las tierras altas conocido por sus lagos, clima templado y cultura indígena Tzeltal. Famoso por sus arreglos florales y proximidad a las impresionantes Lagunas de Montebello, reserva natural de importancia internacional.', dates: 'Visitable Todo el Año', municipality: 'Comitán de Domínguez',        tags: ['Lagos', 'Naturaleza', 'Ecoturismo', 'Paisajes'],            specialty: 'Naturaleza y Lagos',       history: 'Fundada en 1564, es la puerta de entrada a las más hermosas reservas naturales de Chiapas.',                                                   photos: festivalPhotos.comitan },
      villaflores:  { type: 'Festival Agrícola',       title: 'Festival del Café',           text: 'Este paraíso agrícola es conocido como la capital del café de Chiapas, produciendo algunos de los mejores granos arábigos de México. La región ofrece festivales de café, turismo ecológico y catas de café de alta calidad en fincas históricas.',   dates: 'Mayo - Junio',           municipality: 'Villaflores',                 tags: ['Café', 'Agricultura', 'Degustación', 'Agroturismo'],        specialty: 'Café Premium',             history: 'Desde 1900, el cultivo del café ha moldeado la identidad de esta región cafetalera.',                                                          photos: festivalPhotos.villaflores },
      tapachula:    { type: 'Festival Agrícola',       title: 'Festival del Cacao',          text: 'La ciudad más tropical de Chiapas, ubicada en la frontera con Guatemala. Conocida por las plantaciones de cacao, mercados vibrantes y festividades que celebran el cacao. Centro importante de comercio e intercambio cultural entre México y América Central.',    dates: 'Junio - Julio',         municipality: 'Tapachula',                   tags: ['Cacao', 'Comercio', 'Tropical', 'Mercados'],                specialty: 'Cacao y Comercio',         history: 'Un antiguo asentamiento Maya que se convirtió en un importante puesto comercial regional de chocolate y cacao.',                               photos: festivalPhotos.tapachula },
      margaritas:   { type: 'Festividades Indígenas',  title: 'Festividades Indígenas',      text: 'Una comunidad de las tierras altas conocida por sus tradiciones indígenas Tzeltal, tejidos tradicionales y celebraciones comunitarias auténticas. La ciudad ofrece a los visitantes una visión genuina de la vida indígena contemporánea con festividades durante todo el año.', dates: 'Todo el Año', municipality: 'Las Margaritas',              tags: ['Tejidos', 'Artesanías', 'Cultura Viva', 'Tradición'],       specialty: 'Tejidos Tradicionales',    history: 'Un ejemplo vivo de cómo las tradiciones indígenas continúan floreciendo en Chiapas moderno.',                                                  photos: festivalPhotos.margaritas },
    },
  },
  en: {
    sectionLabel: 'Festivals',
    footerBrand: 'Chiapas · Mexico',
    aboutTitle: 'About Chiapas',
    aboutText: 'Chiapas is a land of ancient cultures, vibrant traditions, and breathtaking natural beauty. This southern Mexican state is home to the Mayan and Tzeltal civilizations, whose heritage is celebrated through colorful festivals and sacred rituals throughout the year. From colonial cities to indigenous highlands, Chiapas is where Mexico\'s heart beats strongest.',
    festivals: ['Parachicos - Grand Festival', 'Tzotzil Carnival', 'Ocozocoautla Carnival', 'Spring Fair', 'Patron Saint Festivals', 'Palenque Ruins', 'Montebello Lakes', 'Coffee Festival', 'Cacao Festival', 'Indigenous Festivities'],
    data: {
      parachicos:   { type: 'UNESCO Heritage',          title: 'Parachicos - Grand Festival', text: 'The legendary Fiesta Grande de Chiapa de Corzo where the iconic Parachicos dance comes alive every January. Recognized by UNESCO in 2010 as Intangible Cultural Heritage of Humanity. Includes music, dance, gastronomy and religious celebration.',                                                               dates: 'January 7 - 23',         municipality: 'Chiapa de Corzo',              tags: ['Traditional Dance', 'UNESCO', 'January', 'Heritage'],       specialty: 'Parachicos Dance',         history: 'This colonial gem sits on the Grijalva River with 500+ years of festive tradition.',                                                           photos: festivalPhotos.parachicos },
      chamula:      { type: 'Indigenous Festival',      title: 'Tzotzil Carnival',            text: 'Famous for its Tzotzil Carnival, one of the most spectacular festivals in Mexico. The Pasiones dance for days in honor of the sun, blending Mayan and Catholic rites in perfect harmony. A spectacle of color and tradition unparalleled in Mexico.',        dates: 'Late February',          municipality: 'San Juan Chamula',             tags: ['Tzotzil Carnival', 'Ritual Dance', 'Sacred', 'Ritual'],     specialty: 'Indigenous Rituals',       history: 'A sacred Tzotzil community in the highlands with unbroken pre-Hispanic traditions.',                                                           photos: festivalPhotos.chamula },
      ocozocoautla: { type: 'Regional Carnival',        title: 'Ocozocoautla Carnival',       text: 'Affectionately known as Coita, its carnival features the stunning Quexquemetl dance and local Parachicos, a vibrant celebration mixing humor, music, marimba and authentic folk traditions. A festival of colors and movement.',                             dates: 'February',               municipality: 'Ocozocoautla de Espinosa',    tags: ['Carnival', 'Dance', 'Tradition', 'Humor'],                  specialty: 'Folk Dance',               history: 'A mestizo community famous for blending indigenous and Spanish cultural elements.',                                                             photos: festivalPhotos.ocozocoautla },
      tuxtla:       { type: 'State Fair',               title: 'Spring Fair',                 text: 'Capital of Chiapas, this modern city hosts the famous Spring and Peace Fair annually, bringing together traditions, crafts, local gastronomy and spectacular cultural shows. A week of total celebration.',                                                  dates: 'March - April',          municipality: 'Tuxtla Gutiérrez',            tags: ['Fair', 'Gastronomy', 'Crafts', 'Music'],                    specialty: 'Fair & Commerce',          history: 'Founded in 1565, it is the most important fair center in Chiapas and the state\'s economic capital.',                                         photos: festivalPhotos.tuxtla },
      sancristobal: { type: 'Religious Festivities',    title: 'Patron Saint Festivals',      text: 'A beautiful colonial center at 7,200 ft elevation, full of religious festivals year-round. Each neighborhood honors its patron saint with marimba, fireworks, processions and traditional fairs. A complete year of celebrations.',                           dates: 'Year-round',             municipality: 'San Cristóbal de las Casas',  tags: ['Patron Festivals', 'Marimba', 'Religious', 'Processions'],  specialty: 'Colonial Heritage',        history: 'Founded in 1528, it remains the cultural heart of the Chiapas highlands.',                                                                    photos: festivalPhotos.sancristobal },
      palenque:     { type: 'Archaeological Site',      title: 'Palenque Ruins',              text: 'Home to one of the most important and enigmatic Mayan ruins in Mexico. The ancient city of Bakal reveals stunning temples, palaces, and hieroglyphic inscriptions in a jungle setting lost to time. A UNESCO World Heritage Site.',               dates: 'Visitable Year-round',   municipality: 'Palenque',                    tags: ['Mayan Ruins', 'Archaeology', 'Jungle', 'Heritage'],         specialty: 'Ancient Mayan Culture',    history: 'The city peaked from 600-800 AD, representing the height of Classic Mayan civilization.',                                                     photos: festivalPhotos.palenque },
      comitan:      { type: 'Ecotourism Destination',   title: 'Montebello Lakes',            text: 'A charming colonial town in the highlands known for its lakes, temperate climate, and indigenous Tzeltal culture. Famous for its floral arrangements and proximity to the stunning Montebello Lakes, an international natural reserve.',                   dates: 'Visitable Year-round',   municipality: 'Comitán de Dominguez',        tags: ['Lakes', 'Nature', 'Ecotourism', 'Landscapes'],              specialty: 'Nature & Lakes',           history: 'Founded in 1564, it is a gateway to Chiapas\' most beautiful natural reserves.',                                                              photos: festivalPhotos.comitan },
      villaflores:  { type: 'Agricultural Festival',    title: 'Coffee Festival',             text: 'This agricultural paradise is known as the coffee capital of Chiapas, producing some of Mexico\'s finest arabica beans. The region offers coffee festivals, ecological tourism and tastings at historic plantations and roasteries.',                      dates: 'May - June',             municipality: 'Villaflores',                 tags: ['Coffee', 'Agriculture', 'Tasting', 'Agrotourism'],          specialty: 'Premium Coffee',           history: 'Since 1900, coffee cultivation has shaped the identity of this premier coffee region.',                                                        photos: festivalPhotos.villaflores },
      tapachula:    { type: 'Agricultural Festival',    title: 'Cacao Festival',              text: 'Chiapas\' most tropical city, located on the Guatemala border. Known for cacao plantations, vibrant markets and festivities celebrating cacao. An important center of commerce and cultural exchange between Mexico and Central America.',              dates: 'June - July',            municipality: 'Tapachula',                   tags: ['Cacao', 'Trade', 'Tropical', 'Markets'],                    specialty: 'Cacao & Commerce',         history: 'An ancient Mayan settlement that became a vital trading post for regional cacao and chocolate commerce.',                                      photos: festivalPhotos.tapachula },
      margaritas:   { type: 'Indigenous Festivities',   title: 'Indigenous Festivities',      text: 'A highland community known for its indigenous Tzeltal traditions, traditional weaving, and authentic community celebrations. The town offers visitors a genuine glimpse into contemporary indigenous life with festivities throughout the entire year.',          dates: 'Year-round',             municipality: 'Las Margaritas',              tags: ['Weaving', 'Crafts', 'Living Culture', 'Tradition'],         specialty: 'Traditional Weaving',      history: 'A living example of how indigenous traditions continue to thrive in modern Chiapas.',                                                          photos: festivalPhotos.margaritas },
    },
  },
  pt: {
    sectionLabel: 'Festivais',
    footerBrand: 'Chiapas · México',
    aboutTitle: 'Sobre Chiapas',
    aboutText: 'Chiapas é uma terra de culturas ancestrais, tradições vibrantes e beleza natural impressionante. Este estado do sul do México é lar das civilizações Maia e Tzeltal, cujo patrimônio é celebrado através de festivais coloridos e rituais sagrados o ano todo. Das cidades coloniais às terras altas indígenas, Chiapas é onde o coração do México bate mais forte.',
    festivals: ['Parachicos - Festa Grande', 'Carnaval Tzotzil', 'Carnaval Ocozocoautla', 'Feira da Primavera', 'Festas Patronais', 'Ruínas de Palenque', 'Lagoas de Montebello', 'Festival do Café', 'Festival do Cacau', 'Festividades Indígenas'],
    data: {
      parachicos:   { type: 'Patrimônio UNESCO',        title: 'Parachicos - Festa Grande',   text: 'A lendária Fiesta Grande de Chiapa de Corzo onde a icônica dança dos Parachicos cobra vida a cada janeiro. Reconhecida pela UNESCO em 2010 como Patrimônio Cultural Imaterial da Humanidade. Inclui música, dança, gastronomia e celebração religiosa.',                                                          dates: '7 - 23 de Janeiro',      municipality: 'Chiapa de Corzo',              tags: ['Dança Tradicional', 'UNESCO', 'Janeiro', 'Patrimônio'],     specialty: 'Dança Parachicos',         history: 'Esta joia colonial fica no Rio Grijalva com mais de 500 anos de tradição festiva.',                                                            photos: festivalPhotos.parachicos },
      chamula:      { type: 'Festival Indígena',        title: 'Carnaval Tzotzil',            text: 'Famoso pelo Carnaval Tzotzil, um dos festivais mais espetaculares do México. Os Pasiones dançam por dias em honra ao sol, fundindo ritos maias com elementos católicos em perfeita harmonia. Um espetáculo de cor e tradição sem igual.',              dates: 'Fins de Fevereiro',      municipality: 'San Juan Chamula',             tags: ['Carnaval Tzotzil', 'Dança Ritual', 'Sagrado', 'Ritual'],    specialty: 'Rituais Indígenas',        history: 'Uma comunidade Tzotzil sagrada nas terras altas com tradições pré-hispânicas ininterruptas.',                                                  photos: festivalPhotos.chamula },
      ocozocoautla: { type: 'Carnaval Regional',        title: 'Carnaval Ocozocoautla',       text: 'Conhecida carinhosamente como Coita, seu carnaval destaca a dança Quexquemetl e Parachicos locais, uma celebração vibrante misturando humor, música, marimba e tradição popular autêntica. Uma festa de cores e movimento.',                  dates: 'Fevereiro',              municipality: 'Ocozocoautla de Espinosa',    tags: ['Carnaval', 'Dança', 'Tradição', 'Humor'],                   specialty: 'Dança Popular',            history: 'Uma comunidade mestiça famosa por fundir elementos culturais indígenas e espanhóis.',                                                           photos: festivalPhotos.ocozocoautla },
      tuxtla:       { type: 'Feira Estadual',           title: 'Feira da Primavera',          text: 'Capital de Chiapas, essa cidade moderna realiza anualmente a famosa Feira da Primavera e da Paz, reunindo tradições, artesanato, gastronomia local e espetáculos culturais espetaculares. Uma semana de celebração total.',                          dates: 'Março - Abril',          municipality: 'Tuxtla Gutiérrez',            tags: ['Feira', 'Gastronomia', 'Artesanato', 'Música'],             specialty: 'Comércio e Feiras',        history: 'Fundada em 1565, é o centro político e econômico do estado e a maior feira de Chiapas.',                                                       photos: festivalPhotos.tuxtla },
      sancristobal: { type: 'Festividades Religiosas',  title: 'Festas Patronais',            text: 'Uma linda cidade colonial a 2.200m de altitude, repleta de festividades religiosas o ano todo. Cada bairro honra seu santo padroeiro com marimba, fogos, procissões e feiras tradicionais. Um ano completo de celebrações.',                     dates: 'O Ano Inteiro',          municipality: 'San Cristóbal de las Casas',  tags: ['Festas Patronais', 'Marimba', 'Religioso', 'Procissões'],   specialty: 'Patrimônio Colonial',      history: 'Fundada em 1528, permanece sendo o coração cultural das terras altas de Chiapas.',                                                             photos: festivalPhotos.sancristobal },
      palenque:     { type: 'Sítio Arqueológico',       title: 'Ruínas de Palenque',          text: 'Lar de uma das ruínas Maias mais importantes e enigmáticas do México. A antiga cidade de Bakal revela templos deslumbrantes, palacios e inscrições hieroglíficas perdidos na selva há séculos. Um Patrimônio da Humanidade.',                         dates: 'Visitável O Ano Inteiro', municipality: 'Palenque',                   tags: ['Ruínas Maias', 'Arqueologia', 'Selva', 'Patrimônio'],       specialty: 'Cultura Maia Ancestral',   history: 'O auge da cidade foi de 600-800 dC, representando a altura da civilização Maia Clássica.',                                                     photos: festivalPhotos.palenque },
      comitan:      { type: 'Destino de Ecoturismo',    title: 'Lagoas de Montebello',        text: 'Uma charmosa cidade colonial nas terras altas conhecida por seus lagos, clima temperado e cultura indígena Tzeltal. Famosa por seus arranjos florais e proximidade às impressionantes Lagoas de Montebello, uma reserva natural internacional.',         dates: 'Visitável O Ano Inteiro', municipality: 'Comitán de Dominguez',       tags: ['Lagos', 'Natureza', 'Ecoturismo', 'Paisagens'],             specialty: 'Natureza e Lagos',         history: 'Fundada em 1564, é porta de entrada para as mais belas reservas naturais de Chiapas.',                                                         photos: festivalPhotos.comitan },
      villaflores:  { type: 'Festival Agrícola',        title: 'Festival do Café',            text: 'Este paraíso agrícola é conhecido como a capital do café de Chiapas, produzindo alguns dos melhores grãos arábicos do México. A região oferece festivais de café, turismo ecológico e degustações em fazendas e torrefações históricas.',        dates: 'Maio - Junho',           municipality: 'Villaflores',                 tags: ['Café', 'Agricultura', 'Degustação', 'Agroturismo'],         specialty: 'Café Premium',             history: 'Desde 1900, o cultivo de café moldou a identidade dessa região cafeeira por excelência.',                                                      photos: festivalPhotos.villaflores },
      tapachula:    { type: 'Festival Agrícola',        title: 'Festival do Cacau',           text: 'A cidade mais tropical de Chiapas, localizada na fronteira com a Guatemala. Conhecida por plantações de cacau, mercados vibrantes e festividades que celebram o cacau. Um centro importante de comércio e intercâmbio cultural entre México e América Central.',  dates: 'Junho - Julho',         municipality: 'Tapachula',                   tags: ['Cacau', 'Comércio', 'Tropical', 'Mercados'],                specialty: 'Cacau e Comércio',         history: 'Um antigo assentamento Maia que se tornou um importante posto comercial regional de cacau e chocolate.',                                       photos: festivalPhotos.tapachula },
      margaritas:   { type: 'Festividades Indígenas',   title: 'Festividades Indígenas',      text: 'Uma comunidade das terras altas conhecida por suas tradições indígenas Tzeltal, tecelagem tradicional e celebrações autênticas da comunidade. Oferece aos visitantes um vislumbre genuíno da vida indígena contemporânea com festividades o ano todo.',  dates: 'O Ano Inteiro',         municipality: 'Las Margaritas',              tags: ['Tecelagem', 'Artesanato', 'Cultura Viva', 'Tradição'],      specialty: 'Tecelagem Tradicional',    history: 'Um exemplo vivo de como as tradições indígenas continuam florescendo em Chiapas moderna.',                                                     photos: festivalPhotos.margaritas },
    },
  },
}

export const FESTIVAL_KEYS: string[] = ['parachicos', 'chamula', 'ocozocoautla', 'tuxtla', 'sancristobal', 'palenque', 'comitan', 'villaflores', 'tapachula', 'margaritas']

export const LANGUAGES: Language[] = [
  { code: 'es', label: 'ES', title: 'Español' },
  { code: 'en', label: 'EN', title: 'English' },
  { code: 'pt', label: 'PT', title: 'Português' },
]
